# Generated by Django 4.2.2 on 2023-07-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='nombre')),
                ('type', models.CharField(choices=[('G', 'Reg. General'), ('E', 'Reg. Esp. Agrario')], max_length=1, verbose_name='tipo')),
                ('vat', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='%IVA')),
                ('irpf', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='%IRPF')),
            ],
            options={
                'verbose_name': 'Régimen',
                'verbose_name_plural': 'Regímenes',
            },
        ),
        migrations.DeleteModel(
            name='AsientoPrueba',
        ),
    ]
