# Generated by Django 4.2.2 on 2023-07-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_regime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='regime',
            name='serial',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='serie'),
        ),
    ]
