# Generated by Django 4.2.2 on 2023-07-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_regime_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regime',
            name='serial',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='serie'),
        ),
    ]
