# Generated by Django 4.2.2 on 2023-07-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='serial',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_start',
            field=models.DateField(null=True, verbose_name='inicio fiscal'),
        ),
    ]
