# Generated by Django 4.2.2 on 2023-07-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_company_address_line2_alter_company_post_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address_line2',
            field=models.CharField(blank=True, max_length=46, verbose_name='línea extra'),
        ),
    ]
