# Generated by Django 4.2.2 on 2023-07-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_company_options_alter_company_post_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='invoice_line',
            field=models.CharField(blank=True, max_length=128, verbose_name='línea extra factura'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_line2',
            field=models.CharField(blank=True, max_length=46, verbose_name='línea extra dirección'),
        ),
    ]
