# Generated by Django 4.2.2 on 2023-07-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_company_invoice_line_alter_company_address_line2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='invoice_line',
            field=models.TextField(blank=True, max_length=256, verbose_name='línea extra factura'),
        ),
    ]
