# Generated by Django 4.2.2 on 2023-07-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_company_invoice_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='invoice_line',
            field=models.TextField(blank=True, max_length=182, verbose_name='línea extra factura'),
        ),
    ]
