# Generated by Django 4.2.2 on 2023-08-01 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_agent_country'),
        ('accounts', '0012_alter_company_invoice_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='supplier',
        ),
        migrations.AddField(
            model_name='user',
            name='agent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.agent', verbose_name='agente'),
        ),
    ]
