# Generated by Django 4.2.2 on 2023-07-17 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('purchases', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('agent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.agent')),
            ],
            options={
                'verbose_name': 'Laboratorio',
            },
            bases=('base.agent',),
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='nombre')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.supplier', verbose_name='Agricultor')),
            ],
            options={
                'verbose_name': 'finca',
                'verbose_name_plural': 'fincas',
            },
        ),
        migrations.CreateModel(
            name='QualityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'tipo de calidad',
                'verbose_name_plural': 'tipos de calidad',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='nombre')),
                ('agrofoodtypes', models.ManyToManyField(related_name='warehouses', to='product.agrofoodtype', verbose_name='tipo de género')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.land', verbose_name='finca')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality.qualitytype', verbose_name='calidad')),
            ],
            options={
                'verbose_name': 'nave',
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchases.entry', verbose_name='Entrada')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality.lab', verbose_name='laboratorio')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quality.warehouse', verbose_name='Nave')),
            ],
            options={
                'verbose_name': 'Análisis',
                'verbose_name_plural': 'Análisis',
            },
        ),
    ]
