# Generated by Django 4.2.2 on 2023-06-22 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='nombre')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.supplier', verbose_name='Agricultor')),
            ],
            options={
                'verbose_name': 'finca',
                'verbose_name_plural': 'fincas',
            },
        ),
        migrations.CreateModel(
            name='QualityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'tipo de calidad',
                'verbose_name_plural': 'tipos de calidad',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='nombre')),
                ('agrofood_types', models.ManyToManyField(related_name='warehouses', to='product.agrofoodtype', verbose_name='tipo de género')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.land', verbose_name='finca')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality.qualitytype', verbose_name='calidad')),
            ],
            options={
                'verbose_name': 'nave',
                'verbose_name_plural': 'naves',
            },
        ),
    ]
