# Generated by Django 4.2.2 on 2023-07-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_agrofoodsubfamily_family_and_more'),
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='agrofoodtypes',
            field=models.ManyToManyField(to='product.agrofoodtype', verbose_name='tipo de género'),
        ),
    ]
