# Generated by Django 4.2.2 on 2023-06-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='agrofood_types',
            new_name='agrofoodtypes',
        ),
    ]
