# Generated by Django 4.2.2 on 2023-06-26 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_alter_entry_agrofood_alter_entry_entrynote_and_more'),
        ('base', '0001_initial'),
        ('quality', '0003_remove_qualitytype_value_qualitytype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('agent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.agent')),
            ],
            options={
                'verbose_name': 'Laboratorio',
            },
            bases=('base.agent',),
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'nave'},
        ),
        migrations.AlterField(
            model_name='qualitytype',
            name='name',
            field=models.CharField(max_length=256, verbose_name='nombre'),
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='fecha')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchases.entry', verbose_name='Entrada')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality.lab', verbose_name='laboratorio')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quality.warehouse', verbose_name='Nave')),
            ],
        ),
    ]
