# Generated by Django 4.2.2 on 2023-06-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0004_lab_alter_warehouse_options_alter_qualitytype_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'verbose_name': 'Análisis', 'verbose_name_plural': 'Análisis'},
        ),
        migrations.AlterField(
            model_name='analysis',
            name='date',
            field=models.DateField(verbose_name='fecha'),
        ),
    ]
