# Generated by Django 4.2.2 on 2023-06-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packaging',
            name='type',
            field=models.CharField(choices=[('box', 'Caja'), ('pallet', 'Pallet')], max_length=32, verbose_name='tipo'),
        ),
    ]
