# Generated by Django 4.2.2 on 2023-08-01 15:20

import archive.pdfutils.filepath
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=256, upload_to=archive.pdfutils.filepath.get_filepath, verbose_name='archivo'),
        ),
    ]
