# Generated by Django 4.2.2 on 2023-06-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packaging',
            options={'verbose_name': 'envase'},
        ),
        migrations.AlterField(
            model_name='packaging',
            name='material',
            field=models.CharField(choices=[('plastico', 'Plástico'), ('madera', 'Madera'), ('carton', 'Cartón'), ('ifco', 'IFCO')], max_length=32, verbose_name='material'),
        ),
    ]
