# Generated by Django 4.2.2 on 2023-11-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0002_transaction_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='packaging',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='total'),
        ),
    ]
