# Generated by Django 4.2.2 on 2023-11-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0003_packaging_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='corrective',
            field=models.BooleanField(default=False, verbose_name='corrective'),
        ),
    ]
