# Generated by Django 4.2.2 on 2023-11-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0004_transaction_corrective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='corrective',
            field=models.BooleanField(default=False, verbose_name='corrección saldo'),
        ),
    ]
