# Generated by Django 4.2.2 on 2023-11-29 10:58

import archive.pdfutils.filepath
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0005_alter_transaction_corrective'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, max_length=256, upload_to=archive.pdfutils.filepath.get_filepath, verbose_name='archivo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='pdf_file',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='packaging',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='packaging.packaging', verbose_name='tipo'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='packaging.transactiongroup'),
        ),
    ]
