# Generated by Django 4.2.2 on 2023-12-05 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_agent_country'),
        ('packaging', '0009_transactiongroup_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiongroup',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.agent', verbose_name='agente'),
        ),
        migrations.AlterField(
            model_name='transactiongroup',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha'),
        ),
    ]
