# Generated by Django 4.2.2 on 2023-07-17 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packaging', '0001_initial'),
        ('base', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierAgent',
            fields=[
                ('agent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.agent')),
                ('carrier_price', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='precio porte')),
            ],
            options={
                'verbose_name': 'transportista',
            },
            bases=('base.agent', models.Model),
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='nombre')),
                ('comision', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='COMISIÓN')),
                ('descarga', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='DESCARGA')),
                ('analisis', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='ANÁLISIS')),
                ('portes', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='PORTES')),
                ('embalajes', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='EMBALAJES')),
            ],
            options={
                'verbose_name': 'tarifa',
            },
        ),
        migrations.CreateModel(
            name='SupplierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'agrupación',
                'verbose_name_plural': 'agrupaciones',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('agent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.agent')),
                ('share', models.SmallIntegerField(blank=True, null=True, verbose_name='porcentaje de reparto')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchases.carrieragent', verbose_name='transportista')),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.charge', verbose_name='tarifa')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='purchases.suppliergroup', verbose_name='agrupación')),
            ],
            options={
                'verbose_name': 'agricultor',
                'verbose_name_plural': 'agricultores',
            },
            bases=('base.agent', models.Model),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settled', models.BooleanField(default=False, verbose_name='liquidada')),
                ('paid', models.BooleanField(default=False, verbose_name='pagada')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.supplier')),
            ],
            options={
                'verbose_name': 'Factura',
            },
        ),
        migrations.CreateModel(
            name='EntryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_price', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='precio porte')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('registered', models.BooleanField(default=False, verbose_name='registrado')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchases.carrieragent', verbose_name='transportista')),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.charge', verbose_name='tarifa')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrynotes', to='purchases.invoice', verbose_name='factura')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.supplier', verbose_name='agricultor')),
            ],
            options={
                'verbose_name': 'Albarán',
                'verbose_name_plural': 'Albaranes',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='peso neto')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='precio por kg')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('agrofood', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.agrofoodtype', verbose_name='género')),
                ('entrynote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.entrynote', verbose_name='albarán')),
                ('packaging_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='packaging.transaction')),
            ],
            options={
                'verbose_name': 'entrada',
            },
        ),
    ]
