# Generated by Django 4.2.2 on 2023-06-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='num_packages',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='packaging',
        ),
        migrations.AddField(
            model_name='entry',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='precio por kg'),
        ),
    ]
