# Generated by Django 4.2.2 on 2023-06-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_remove_entry_num_packages_remove_entry_packaging_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha'),
        ),
    ]
