# Generated by Django 4.2.2 on 2023-06-25 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_remove_supplier_carrier_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='entry_note',
            new_name='entrynote',
        ),
    ]
