# Generated by Django 4.2.2 on 2023-07-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_invoice_number_invoice_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='serial',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True, verbose_name='serie factura'),
        ),
    ]
