# Generated by Django 4.2.2 on 2023-06-26 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_agrofoodtype_packaging'),
        ('quality', '0003_remove_qualitytype_value_qualitytype_name'),
        ('purchases', '0004_rename_entry_note_entry_entrynote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='agrofood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.agrofoodtype', verbose_name='género'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entrynote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.entrynote', verbose_name='albarán'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quality.warehouse', verbose_name='nave'),
        ),
    ]
