# Generated by Django 4.2.2 on 2023-06-16 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0002_alter_packaging_options_alter_packaging_material'),
        ('purchases', '0004_alter_entry_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='packaging_transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='packaging.transaction'),
        ),
    ]
