# Generated by Django 4.2.2 on 2023-07-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_supplier_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='serial',
            field=models.CharField(max_length=3, unique=True, verbose_name='serie factura'),
        ),
    ]
