# Generated by Django 4.2.2 on 2023-06-16 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0002_alter_packaging_options_alter_packaging_material'),
        ('purchases', '0005_entry_packaging_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='packaging_transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='packaging.transaction'),
        ),
    ]
