# Generated by Django 4.2.2 on 2023-07-17 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_alter_supplier_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='share',
        ),
    ]
