# Generated by Django 4.2.2 on 2023-06-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_alter_entry_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='precio por kg'),
        ),
    ]
