# Generated by Django 4.2.2 on 2023-07-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_remove_supplier_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='suppliergroup',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='nombre'),
        ),
    ]
