# Generated by Django 4.2.2 on 2023-07-18 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_regime_type'),
        ('purchases', '0007_alter_charge_name_alter_suppliergroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='regime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.regime', verbose_name='régimen'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchases.suppliergroup', verbose_name='agrupación'),
        ),
    ]
