# Generated by Django 4.2.2 on 2023-07-18 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_regime_type'),
        ('purchases', '0008_supplier_regime_alter_supplier_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='regime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.regime', verbose_name='régimen'),
        ),
    ]
