# Generated by Django 4.2.2 on 2023-07-18 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_regime_type'),
        ('purchases', '0009_alter_supplier_regime'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='regime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.regime'),
        ),
    ]
