# Generated by Django 4.2.2 on 2023-07-12 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0010_alter_entry_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='purchases.supplier'),
        ),
        migrations.AlterField(
            model_name='entrynote',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrynotes', to='purchases.invoice', verbose_name='factura'),
        ),
        migrations.AlterField(
            model_name='entrynote',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.supplier', verbose_name='agricultor'),
        ),
    ]
