# Generated by Django 4.2.2 on 2023-07-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0012_remove_invoice_regime_invoice_base_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='base_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='expenses_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='irpf_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='vat_amount',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('G', 'Reg. General'), ('E', 'Reg. Esp. Agrario')], max_length=1, verbose_name='tipo'),
        ),
    ]
