# Generated by Django 4.2.2 on 2023-07-19 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0013_remove_invoice_base_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'factura'},
        ),
        migrations.AddField(
            model_name='entrynote',
            name='analisis',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='ANÁLISIS'),
        ),
        migrations.AddField(
            model_name='entrynote',
            name='comision',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='COMISIÓN'),
        ),
        migrations.AddField(
            model_name='entrynote',
            name='descarga',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='DESCARGA'),
        ),
        migrations.AddField(
            model_name='entrynote',
            name='embalajes',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='EMBALAJES'),
        ),
        migrations.AddField(
            model_name='entrynote',
            name='portes',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='PORTES'),
        ),
        migrations.AlterField(
            model_name='entrynote',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.invoice', verbose_name='factura'),
        ),
    ]
