# Generated by Django 4.2.2 on 2023-07-20 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0001_initial'),
        ('purchases', '0015_alter_charge_comision_alter_entrynote_comision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='comision',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='COMISIÓN'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='packaging_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='packaging.transaction', verbose_name='Envases'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='entrynote',
            name='comision',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='COMISIÓN'),
        ),
    ]
