# Generated by Django 4.2.2 on 2023-07-26 13:48

import archive.pdfutils.filepath
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0023_alter_settlement_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='doc_link',
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=256, upload_to=archive.pdfutils.filepath.get_filepath, verbose_name='archivo'),
        ),
    ]
