# Generated by Django 4.2.2 on 2023-07-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0026_remove_supplier_serial_alter_invoice_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='serial',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='serie'),
        ),
    ]
