# Generated by Django 4.2.2 on 2023-06-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exit',
            options={'verbose_name': 'salida'},
        ),
        migrations.RenameField(
            model_name='exit',
            old_name='price_per_kg',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='exit',
            old_name='net_weight',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='exit',
            name='num_packages',
        ),
        migrations.RemoveField(
            model_name='exit',
            name='packaging',
        ),
        migrations.AlterField(
            model_name='exit',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha'),
        ),
    ]
