# Generated by Django 4.2.2 on 2023-06-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exit',
            name='weight',
            field=models.DecimalField(decimal_places=0, max_digits=8, verbose_name='peso neto'),
        ),
    ]
