# Generated by Django 4.2.2 on 2023-06-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_exit_options_rename_price_per_kg_exit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exit',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha'),
        ),
    ]
