# Generated by Django 4.2.2 on 2023-07-24 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_exit_packaging_transaction_alter_exit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exit',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='exit',
            name='weight',
            field=models.DecimalField(decimal_places=0, max_digits=8, validators=[django.core.validators.MinValueValidator(1)], verbose_name='peso neto'),
        ),
    ]
