# Generated by Django 4.2.2 on 2023-07-24 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrofoodsubfamily',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.agrofoodfamily', verbose_name='familia'),
        ),
        migrations.AlterField(
            model_name='agrofoodtype',
            name='subfamily',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.agrofoodsubfamily', verbose_name='subfamilia'),
        ),
    ]
