# Generated by Django 4.2.2 on 2023-06-24 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0002_alter_packaging_type'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrofoodtype',
            name='packaging',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='packaging.packaging', verbose_name='envase'),
        ),
    ]
