# Generated by Django 4.2.2 on 2023-06-22 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='nombre')),
                ('cif', models.CharField(blank=True, max_length=16, verbose_name='cif/nif')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='dirección')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='teléfono')),
                ('mobile', models.CharField(blank=True, max_length=64, verbose_name='móvil')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fax', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('agent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.agent')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='base.agent')),
            ],
            options={
                'verbose_name': 'contacto',
            },
            bases=('base.agent',),
        ),
    ]
