# Generated by Django 4.2.2 on 2023-07-17 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, choices=[('ES', 'España')], max_length=2, verbose_name='país')),
                ('postal_code', models.CharField(blank=True, max_length=5, verbose_name='código postal')),
                ('state', models.CharField(blank=True, choices=[('ES', 'España')], max_length=30, verbose_name='provincia')),
                ('city', models.CharField(blank=True, choices=[('ES', 'España')], max_length=30, verbose_name='población')),
                ('address_line', models.CharField(blank=True, choices=[('ES', 'España')], max_length=46, verbose_name='dirección')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='nombre')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='teléfono')),
                ('mobile', models.CharField(blank=True, max_length=64, verbose_name='telf. móvil')),
                ('cif', models.CharField(blank=True, max_length=16, verbose_name='cif/nif')),
                ('fax', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='nombre')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='teléfono')),
                ('mobile', models.CharField(blank=True, max_length=64, verbose_name='telf. móvil')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.agent')),
            ],
            options={
                'verbose_name': 'contacto',
            },
        ),
    ]
