# Generated by Django 4.2.2 on 2023-07-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_contact_phone_agent_email_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='address_line',
            field=models.CharField(blank=True, max_length=46, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='city',
            field=models.CharField(blank=True, max_length=30, verbose_name='población'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='state',
            field=models.CharField(blank=True, max_length=30, verbose_name='provincia'),
        ),
    ]
