# Generated by Django 4.2.2 on 2023-07-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_agent_address_line_alter_agent_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='country',
            field=models.CharField(blank=True, choices=[('ES', 'España'), ('PT', 'Portugal'), ('IT', 'Italia')], max_length=2, verbose_name='país'),
        ),
    ]
