# Generated by Django 4.2.2 on 2023-07-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_agent_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='mobile',
            field=models.CharField(blank=True, max_length=32, verbose_name='telf. móvil'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(blank=True, max_length=32, verbose_name='telf. móvil'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='nombre'),
        ),
    ]
