# Generated by Django 4.2.2 on 2023-07-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_agent_mobile_alter_agent_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='country',
            field=models.CharField(blank=True, choices=[('ES', 'ESPAÑA'), ('PT', 'PORTUGAL'), ('IT', 'ITALIA')], max_length=2, verbose_name='país'),
        ),
    ]
